config/routes.rb
Rails.application.routes.draw do
  
  get 'account_settings/account_settings'
  resources :categories
  resources :roles
	get 'about' => 'welcome#about'
	get 'contact' => 'welcome#contact'
	get 'post_novi' => 'posts#new'

	patch 'subscribe' => "account_settings#subs_true"
	patch 'unsubscribe' => "account_settings#subs_false"

	get 'account_settings' => 'account_settings#account_settings'
  get 'drafts' => 'drafts#drafts'
  
  resources :comments
  devise_for :users
  resources :posts

  root to: 'categories#index'
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :category
	belongs_to :user
	has_many :comments, dependent: :destroy

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @user = User.find(current_user.id)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
     @comments = Comment.where("post_id=?", params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id


    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :category_id, :image, :user_id, :published)
    end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, :class => 'ckeditor' %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div class="field">
    Do you want to publish it?
   <%= form.check_box :published, :value => true %>
 </div>

  <div class="field">
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post-preview">
        <a href="post.html">
          <h2 class="post-title">
            <%= link_to post.title, post_path(post) %>
          </h2>
          </a>

          <h3 class="post-subtitle">
            <%= post.body.html_safe %>
          </h3>

        <p class="post-meta">Posted by
          <%= post.user.email %>,
      <%= time_ago_in_words(post.created_at) %> ago

      <% if current_user.role_id != 3 || post.user.email == current_user.email %>
      <%= link_to "edit", edit_post_path(post), class: 'btn btn-white' %>
      <%= link_to "delete", post_path(post), method: :delete, class: 'btn btn-white' , data: { confirm: "Are you sure?"} %>
      <% end %>
      <%= link_to "comment", "comments#new", class: 'btn btn-white' %>

      
</div>

app/views/posts/edit.html.erb
<%= render "layouts/header.html.erb" %>


<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render "layouts/header" %>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <%= render @posts %>
      <hr>
      <!-- Pager -->
      <div class="clearfix">
        
        <% unless current_user.role_id == 3 %>
           <a class="btn btn-primary float-left" href="posts/new">New Post </a>
        <% end %>
        
        <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
      </div>
    </div>
  </div>
</div>

<hr>

app/views/posts/new.html.erb
<%= render "layouts/header.html.erb" %>

<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url('<%= root_url %>img/home-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1><%= @post.title %></h1>
          <span class="subheading"></span>
        </div>
      </div>
    </div>
  </div>
</header>


<p id="notice"><%= notice %></p>



<p>
  <%= @post.body.html_safe %>
</p>

<p>
	<% if @post.image? %>
	<%= image_tag @post.image.url %>
	<% end %>
</p>

<hr>
Komentari:
<%= render @post.comments %>



<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-white' %> |
<%= link_to 'Back', posts_path, class: 'btn btn-white' %> |
<%= link_to 'Comment', comment_url, class: 'btn btn-white' %>





      <!-- Pager -->
      <div class="clearfix">
      </div>
    </div>
  </div>
</div>