config/routes.rb
Rails.application.routes.draw do
  
  get 'account_settings/account_settings'
  resources :categories
  resources :roles
	get 'about' => 'welcome#about'
	get 'contact' => 'welcome#contact'
	get 'post_novi' => 'posts#new'

	patch 'subscribe' => "account_settings#subs_true"
	patch 'unsubscribe' => "account_settings#subs_false"

	get 'account_settings' => 'account_settings#account_settings'
  get 'drafts' => 'drafts#drafts'
  
  resources :comments
  devise_for :users
  resources :posts

  root to: 'categories#index'
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :post, dependent: :destroy

    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @posts = Post.where("category_id=?", params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :post_id, :image)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<tr>
	<td><%= image_tag category.image.url(:medium)%></td>

</tr>
<tr>
	
        <td align="center"><%= link_to category.name, category_path(category), class: 'btn btn-white' %></td>
        <td>Ukupan broj postova: <%= category.post.count %></td>
        <td>Poslednji post kreiran: 
                <% unless !category.post.last %>
                <%= category.post.last.created_at %>
                <% end %>

        </td>
        <% if current_user.role_id == 1 %>
       
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

</tr>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.file_field :image %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>



<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render "layouts/header.html.erb" %>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url('<%= root_url %>img/category-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Categories</h1>
          <span class="subheading"></span>
        </div>
      </div>
    </div>
  </div>
</header>



<h1 align="center">Kategorije postova</h1>

<table>
  <thead>
    <tr>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody align="center">
    <%= render @categories %>
      
 
  </tbody>
</table>

<br>

<% if current_user.role_id == 1 %> 
<%= link_to 'New Category', new_category_path, class: "btn btn-white"%>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<%= render "layouts/header.html.erb" %>

	<h2><%=@category.name%></h2>
	<% @posts.each do |post| %>
        
        <!-- Main Content -->
		<div class="container">
		  <div class="row">
    		<div class="col-lg-8 col-md-10 mx-auto">
      		 

    				<div class="post-preview">
     			   <a href="post.html">
          		<h2 class="post-title">
           			 <%= link_to post.title, post_path(post) %>
          		</h2>
          		</a>

          
        			<p class="post-meta">Posted by
      				<%= post.user.email %>,<%= time_ago_in_words(post.created_at) %> ago
              <% if current_user.role_id =! 3 || post.user.email == current_user.email %>
   			    	<%= link_to "edit", edit_post_path(post), class: 'btn btn-white' %>
     	  		 	<%= link_to "delete", post_path(post), method: :delete, class: 'btn btn-white' , data: { confirm: "Are you sure?"} %>
     			  	<% end %>
              <%= link_to 'comment', comment_path(new_comment_url), class: 'btn btn-white' %>

                    
						</div>



      		<hr>


      		<!-- Pager -->
      		<div class="clearfix">
     			</div>
    		</div>
  		</div>
		</div>
<% end -%>

<% if current_user.role_id != 3 %>
<%= link_to 'New Post', post_novi_url, class: 'btn btn-white' %>
<% end %>

<% if current_user.role_id == 1 %>
<%= link_to 'Edit', edit_category_path(@category) %> 
<% end %>
<%= link_to 'Back', categories_path %>

<hr>