config/routes.rb
Rails.application.routes.draw do
  
  get 'account_settings/account_settings'
  resources :categories
  resources :roles
	get 'about' => 'welcome#about'
	get 'contact' => 'welcome#contact'
	get 'post_novi' => 'posts#new'

	patch 'subscribe' => "account_settings#subs_true"
	patch 'unsubscribe' => "account_settings#subs_false"

	get 'account_settings' => 'account_settings#account_settings'
  get 'drafts' => 'drafts#drafts'
  
  resources :comments
  devise_for :users
  resources :posts

  root to: 'categories#index'
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <ul class="list-inline text-center">
          <li class="list-inline-item">
            <a href="https://twitter.com/">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="https://www.facebook.com/">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="https://github.com/">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted">Copyright &copy; Golux Technologies 2018</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url('<%= root_url %>img/home-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Jana's Blog</h1>
          <span class="subheading"></span>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top", style="color:grey" id="mainNav">
  <div class="container">
    <a class="navbar-brand" style="color:black"  href="<%= root_url %>">
  
      <!--Logovanje-->
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit', edit_user_registration_path %> |
          <%= link_to "Log out", destroy_user_session_path %>
          
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> |
          <%= link_to "Log in", new_user_session_path %>
        <% end %>

    </a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fa fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
         <li class="nav-item">
          <a class="nav-link" style="color:black" href="<%= categories_path %>">Categories</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" style="color:black" href="<%= posts_path %>">Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="color:black" href="<%= about_url %>">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="color:black" href="<%= contact_url %>">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="color:black" href="<%= account_settings_url %>">Account Settings</a>
        </li>

        <%if current_user.role_id != 3 %>
        <li class="nav-item">
          <a class="nav-link" style="color:black" href="<%= drafts_url %>">My Draft Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="color:fuchsia" href="<%= new_post_url %>">New Post</a>
        </li>
        <% end %>

      </ul>
    </div>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  
  <head>
    <title>Bapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% if user_signed_in? %>
    <%= render "layouts/nav.html.erb" %>
    <% end %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
   <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
   <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"> -->

   <!-- Bootstrap core CSS -->
   <link href="<%= root_url%>/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

   <!-- Custom fonts for this template -->
   <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
   <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
   <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

   <!-- Custom styles for this template -->
   <link href="<%= root_url%>/css/clean-blog.min.css" rel="stylesheet">


  </head>



  <body>

        <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <!-- Bootstrap core JavaScript -->
   <script src="<%= root_url%>/vendor/jquery/jquery.min.js"></script>
   <script src="<%= root_url%> /vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

   <!-- Custom scripts for this template -->
   <script src="<%= root_url%>/js/clean-blog.min.js"></script>

   <% if user_signed_in? %>
   <%= render "layouts/footer.html.erb" %>
   <% end %>

  </body>
</html>